# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-hidden-paper-anez0pmn-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b5KaA0wPFQkd

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=${PORT:8080}
